Feat/waitlist
vlecture/vlecture-api pull request #49
Opened 2024-03-23 11:15 UTC by annavaws

## Description
Created a join waitlist endpoint that allows users to submit their email to join waitlist. 

## Usage
### Request Body
Waitlist object example
```
{
  "email": "user@example.com",
}
```

### Response Body
Waitlist response body example
```
{
  "status_code": 200,
  "message": "Joined waitlist successfully"
}
```

## Response Statuses
- `200` SUCCESS Joined waitlist successfully
- `400` FAILED Email already exists in the waitlist
- `422` FAILED Invalid email address

2024-03-23 13:38 UTC, daffafaizan commented
Can you provide the endpoint that we can hit in the description? It'll really help the people coming back to this merge request by making it easy to see what the endpoint is. Thanks!

2024-03-23 15:39 UTC, annavaws commented
> Can you provide the endpoint that we can hit in the description? It'll really help the people coming back to this merge request by making it easy to see what the endpoint is. Thanks!

Good point! Done

2024-03-23 15:54 UTC, daffafaizan approved these changes
Code and changes look good.

2024-03-24 12:12 UTC, jeremyalv requested changes

2024-03-24 12:12 UTC, jeremyalv commented on alembic/versions/6f702f53e396_create_migrations.py
Let's remove this file from the Pull Request, as the changes are already included in the `feat/transcription-update` PR. I've added nullable=True

2024-03-24 12:12 UTC, jeremyalv commented on alembic/versions/6f702f53e396_create_migrations.py
Plus some critical bugfixes were made there

2024-03-24 12:19 UTC, annavaws commented on alembic/versions/6f702f53e396_create_migrations.py
Okay, Done

2024-03-24 13:54 UTC, jeremyalv approved these changes

2024-03-24 13:54 UTC, merged