Feat: Review Flashcards BE
vlecture/vlecture-api pull request #50
Opened 2024-03-24 02:52 UTC by amrul-hzz

Added endpoints, functionalities, and tests for Review Flashcards API:

## Fetch Flashcard Sets
Fetches all flashcard sets created by current user. Accessible through `/v1/flashcards`.

Request body:
```
{
    "user_id" : <insert_user_id>
}
```

## Fetch Flashcards in Set
Fetches all flashcards in the specified flashcard set. Accessible through `/v1/flashcards/set` .

Request body:
```
{
    "note_id" : <insert_note_id>,
    "set_id" : <insert_set_id>
}
```

2024-03-24 07:49 UTC, kausarme commented on src/models/flashcards.py
> +    tags = Column(ARRAY(String), nullable=True, unique=False)
You should consider adding a limit to the length of each tags and the total amount of tags that could be given to a flashcard. This will prevent a spam from adding too many tags.

2024-03-24 07:52 UTC, kausarme commented on src/models/flashcards.py
> +    tags = Column(ARRAY(String), nullable=True, unique=False)
You should consider creating a validation to check that each tag could only be applied to a spesific note only once, as having multiple of the same tag wouldn't make sense.

2024-03-24 12:09 UTC, jeremyalv requested changes

2024-03-24 12:09 UTC, jeremyalv commented on src/controllers/flashcards.py
> +    "/", status_code=http.HTTPStatus.OK, response_model=GenericResponseModel
Let's not use GenericResponseModel, but rather JSONResponse instead (see feat/transcription-update branch => transcription controller)

2024-03-24 12:09 UTC, jeremyalv commented on src/controllers/flashcards.py
> +    response = service.get_flashcard_sets_by_user(
Hm why is this method called twice in the route?

2024-03-24 12:09 UTC, jeremyalv commented on src/main.py
> +    "http://localhost:8000",
Why add port 8000 to sentry though?

2024-03-24 12:09 UTC, jeremyalv commented on src/models/flashcards.py
> +class Flashcard(Base):
Can you add the database migration script (located at `alembic/versions/6f702f53e396_create_vlecture_migrations.py`) for this Model definition?

2024-03-24 12:09 UTC, jeremyalv commented on src/models/flashcards.py
> +class Flashcard(Base):
^ after `feat/transcription-update` PR is merged, because a lot of changes happened there

2024-03-24 12:25 UTC, annavaws commented
Can you add an example for the response body?

2024-03-24 12:30 UTC, annavaws commented on src/models/flashcards.py
> +    rated_difficulty = Column(Enum('hard', 'good', 'easy', name='difficulty_enum'), nullable=True)
Would it be preferable to set the default value for 'rated_difficulty' to 'good' and set nullable as 'False'?

2024-03-27 14:27 UTC, annavaws commented on src/models/flashcards.py
> +    tags = Column(ARRAY(String), nullable=True, unique=False)
What is `tags` used for?

2024-03-29 15:20 UTC, annavaws commented on src/controllers/flashcards.py
> +def view_flashcard_sets(req: FlashcardSetsRequestSchema, session: Session = Depends(get_db)):
Can you modify the function to remove the request body from the GET method? I believe the GET method should not include a request body because it cannot be sent from the frontend. 

```python
def view_flashcard_sets(user: User = Depends(get_current_user), session: Session = Depends(get_db)):
    service = FlashcardService()

    user_id = user.id

    try:
        response = service.get_flashcard_sets_by_user(
            user_id=user_id,
            session=session
        )

```

2024-03-29 16:33 UTC, daffafaizan commented on src/models/flashcards.py
> +    front = Column(String(225), nullable=False)
Isn't 225 characters too limited? I believe it would be better to limit it to 300 characters.

2024-03-29 18:43 UTC, annavaws commented on src/controllers/flashcards.py
> +    "/set", status_code=http.HTTPStatus.OK, response_model=GenericResponseModel
Can you also change this, because I cannot send request body from frontend, so I'm using query. You can check the documentation here https://fastapi.tiangolo.com/tutorial/query-params/

```
python
@flashcards_router.get(
    "/set/{set_id}", status_code=http.HTTPStatus.OK, response_model=GenericResponseModel
)
def view_flashcards(set_id: str, note_id: str = None, user: User = Depends(get_current_user), session: Session = Depends(get_db)):
    service = FlashcardService()

    try:
        user_id = service.get_set_owner(set_id, session)

        if user.id != user_id:
            raise Exception

        response = service.get_flashcards_by_set(
            set_id=set_id,
            note_id=note_id,
            session=session
        )

```

2024-03-29 19:04 UTC, annavaws commented on src/services/flashcards.py
> +    def build_json_flashcard_sets(self, flashcard_sets):
Can you also add this at the code? So that the `date_generated` in response body will be formatted

```python
 def build_json_flashcard_sets(self, flashcard_sets):
        data = []
        for flashcard_set in flashcard_sets:
            formatted_date = datetime.datetime.strftime(
                flashcard_set.date_generated, "%Y-%m-%d %H:%M:%S")
            item = {
                ..  .
                "date_generated": formatted_date,
  
  
```

2024-03-29 20:03 UTC, annavaws commented on src/controllers/flashcards.py
> +    "/set", status_code=http.HTTPStatus.OK, response_model=GenericResponseModel
actually, can you make the router /set/{set_id} (without query note_id) response body including title of the set and note_id? I'm not really understand why you need to put note_id as request body, because the primary key is only set_id right?

2024-03-30 05:56 UTC, amrul-hzz commented on src/controllers/flashcards.py
> +    "/set", status_code=http.HTTPStatus.OK, response_model=GenericResponseModel
The initial design was to make (set_id, note_id) as the composite key for flashcards, but upon further review, I agree that just set_id as the primary key should suffice.

2024-03-30 09:19 UTC, annavaws commented on src/controllers/flashcards.py
> +        title = service.get_set_title
``` python
 title = service.get_set_title(set_id, session)
 note_id = service.get_set_note_id(set_id, session)

response = {
    'title': title,
    'note_id': note_id,
    'flashcards': response
}
``` 
that's how you add a field to a response, also don't forget to pass the set_id and session into get_set_title and get_set_note_id

2024-04-01 02:38 UTC, jeremyalv requested changes

2024-04-01 02:38 UTC, jeremyalv commented on alembic/versions/6f702f53e396_create_vlecture_migrations.py
> +    op.create_table(
![image](https://github.com/vlecture/vlecture-api/assets/42536973/59d373db-3253-487c-9e99-2786b9cfb96d)

Daffa uses "id" only for each of the object's main ID. So instead of `flashcard_id` for flashcard's id, just use ID to avoid redundancy. Same with `flashcard_sets`

2024-04-01 02:38 UTC, jeremyalv commented on src/controllers/transcription.py
> +from src.utils.time import get_datetime_now_jkt
Let's delete this line - Duplicated on line 41

2024-04-01 02:38 UTC, jeremyalv commented on src/models/flashcards.py
> +    set_id = Column(
change `set_id` to just `id` to avoid redundancy

2024-04-01 02:38 UTC, jeremyalv commented on src/models/flashcards.py
> +    flashcard_id = Column(
change `flashcard_id` to just `id` to avoid redundancy

2024-04-01 02:38 UTC, jeremyalv commented on src/models/flashcards.py
> +class DifficultyEnum(Enum):
why create a new table for enum? no need to add `__tablename__`

2024-04-01 02:38 UTC, jeremyalv commented on src/schemas/flashcards.py
> +    flashcard_id: UUID4
can change to `id`

2024-04-01 02:38 UTC, jeremyalv commented on src/services/transcription.py
If there are only formatting changes on this file, please uncommit all its changes. Unless there's something substantive

2024-04-01 06:38 UTC, amrul-hzz commented on src/models/flashcards.py
> +    rated_difficulty = Column(Enum('easy', 'medium', 'hard', 'very hard', name='difficulty_enum'), nullable=False, default='medium')
Noted, I have chosen to add these functionalities in another branch so this one can go ahead with integration.

2024-04-02 06:53 UTC, merged